=head1 INSTALLATION

=head2 Docker image

There is a Dockerfile using which you can easily create a Docker container
containing the search engine and Apache Tika. It needs an external
Elasticsearch instance, for example the "elasticsearch" Docker image.

=head3 Building from the Dockerimage

  cpanm --look Dancer-SearchApp
  cd docker
  docker build .

=head3 Docker image configuration

You pass the IP address and port of the Elasticsearch instance to the
search engine using the C<< --env >> parameter when starting the Docker
image:

  docker run --env SEARCHAPP_ES_NODES=192.168.99.1:9200 -P dsa

=head2 Elasticsearch

Download Elasticsearch from L<https://www.elastic.co/downloads/elasticsearch>

Install and launch Elasticsearch.

=head2 Elasticsearch plugins

=head3 Language detector

L<https://github.com/jprante/elasticsearch-langdetect>

  ./bin/plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/2.1.1.0/elasticsearch-langdetect-2.1.1.0-plugin.zip
  
On Windows

  elasticsearch-2.1.1\bin\plugin.bat install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/2.1.1.0/elasticsearch-langdetect-2.1.1.0-plugin.zip

=head2 Apache Tika

Download the Tika server from L<https://tika.apache.org/download.html>

Current version is

  http://www.apache.org/dyn/closer.cgi/tika/tika-server-1.12.jar

Copy the JAR file into the directory C< jar/> of the distribution.

=head2 Thunderbird link-by-messageid

Install the "Thunderlink" plug-in / add-on for Thunderbird and
register the C<thunderlink://> URI. This allows your browser to directly
display emails in Thunderbird.