=head1 Suchmaschine in Perl

=head1 Zu Viel Information

* Eigentlich: Zu viel _verschiedene_ Information

* Zu wenig Zeit, die Informationen zu organisieren

* Kontext

* Effizienter umschalten

* Schneller finden

* Besser als Google

* Anders als Google

=head1 Existierende Lösungen

=over incremental

* Google Search Appliance

* Zu teuer

* Windows Desktop Search

* Nur Windows / Netzlaufwerke

* Sherlock (Mac)

* Kein Mac

* ??? Linux bzw. Ubuntu

* Kenne ich nicht

=back

=head1 Aufteilung

* Crawler / Importer

* Index

* Suche

=head1 Aufteilung

* Crawler / Importer (Perl)

* Index Elasticsearch

* Suche: Dancer

=head1 Scrapers / Crawlers

* Elemente finden

* Text extrahieren

* Text importieren

* Sprache / Synonyme / URL / Zeitpunkt

* Duplikate! bzw. Reindizierug

=head1 ES Schema

* Subject / Titel

* Body (HTML)

* From / To (???)

* URL / id ( file:// bzw. mail:// )

* type

=head1 Scrapers / Crawlers

* IMAP

* Dateisystem (pdf, Text, Perl)

* HTTP / HTML

* L<HTML::ExtractContent::Pluggable>

=head1 Vergleich mit Google

* Pagerank

* ES rank

* Metasuche

=head1 Metasuche

* Lokale Suche

* Verwenden von ES-Instanzen im lokalen Netzwerk

* Musik

=head1 Content / Testdaten

* Eigene Mails

* Trip zurück ins Jahr 2000

* Nicht gut zur Vorführung

* EU/ESMA produziert viele PDFs

* Ich produziere viele Perl Programme

=head1 Ergebnisse

* PDF

* Mail

* Musik

=head1 Danke
