=head1 Zu Viel Information

* Eigentlich: Zu viel _verschiedene_ Information

* Kontext

* Effizienter umschalten

* Schneller finden

* Besser als Google

* Anders als Google

=head1 Existierende Lösungen

=over incremental

* Google Search Appliance

* Zu teuer

* Windows Desktop Search

* Nur Windows / Netzlaufwerke

* Sherlock (Mac)

* Kein Mac

* ??? Linux bzw. Ubuntu

* Kenne ich nicht

=back

=head1 Aufteilung

* Crawler / Importer

* Index

* Suche

=head1 Aufteilung

* Crawler / Importer (Perl, Java)

* Index Elasticsearch

* Suche: Dancer

=head1 Scrapers / Crawlers

* Elemente finden

* Text extrahieren

* Text importieren

* Sprache / Synonyme / URL / Zeitpunkt

=head1 ES Schema

* Subject

* Body

* From / To (???)

* URL / id

* type

=head1 Scrapers / Crawlers

* IMAP

* Dateisystem (pdf, Text, Perl)

* HTTP / HTML

* L<HTML::ExtractContent::Pluggable>

=head1 Vergleich mit Google

* Pagerank

* ES rank

* Metasuche

=head1 Metasuche

* Lokale Suche

* Verwenden von ES-Instanzen im lokalen Netzwerk

* Musik

=head1 Ergebnisse

* PDF

* Mail

* Musik

=head1 Danke
